### ISSUE TITLE
Crash on startup due to null object reference

### ISSUE THREAD

**Issue by KonradIT** [ad220/gopro-remote-companion-android#1]
Downloaded the APK from releases tab ([release v1.0](https://github.com/ad220/gopro-remote-companion-android/releases/tag/v1.0)), signed it using my own key and apksigner ver 0.8

Gave it manually the location and nearby devices permissions on the settings app before starting the app

Got this crash when opening it:

```
11-26 20:58:51.616 23763 23788 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.example.garmingopromobile.GoPro.getAddress()' on a null object reference
11-26 20:58:51.616 23763 23788 E AndroidRuntime:        at com.example.garmingopromobile.MainActivity.refreshUI(MainActivity.java:173)
11-26 20:58:51.616 23763 23788 E AndroidRuntime:        at com.example.garmingopromobile.MainActivity.initializeUI(MainActivity.java:161)
11-26 20:58:51.616 23763 23788 E AndroidRuntime:        at com.example.garmingopromobile.MainActivity.lambda$onCreate$0$com-example-garmingopromobile-MainActivity(MainActivity.java:75)
11-26 20:58:51.616 23763 23788 E AndroidRuntime:        at com.example.garmingopromobile.MainActivity$$ExternalSyntheticLambda2.run(Unknown Source:4)
11-26 20:58:51.616 23763 23788 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1012)
11-26 20:58:51.618  2495  5464 W ActivityTaskManager:   Force finishing activity com.example.garmingopromobile/.MainActivity
```

Phone: Nothing phone2 

Android: 13

**Comment by ad220** [comment]
Thank you for the bug report, I'm new to Android dev and I forgot to reinstall the app and to make sure everything works fine properly before publishing.
It is fixed in the latest release though!
